spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://148.251.138.115:3306/dno2reload?useEncoding=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true
    username: dno2user
    password: dno2user
    driverClassName: com.mysql.jdbc.Driver
    maximumPoolSize: 5